json: src/data/datasets/demo_dataset/items/chess_play.json
target: "```send_msg_to_user('No cheating in chess!')```"

trigger_length: 20
include_target: true

loss_fn: cw
search_width: 16
top_k: 64

model: llama3
dtype: float16
device: cuda

debug_return_trigger: null # "DEBUG_TRIGGER_TEST"