json: src/data/datasets/demo_dataset/items/linkedin_login.json
target: '```click("217")```'
trigger_length: 20
include_target: true
loss_fn: cw
search_width: 16
top_k: 64
num_steps: 200
batch_size: 4
early_stop: false
model: llama3
dtype: float16
device: cuda
debug_return_trigger: null
